name: CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS v10.24.1
        uses: actions/setup-node@v1
        with:
          node-version: 10.24.1

      - name: Install NPM Packages
        run: npm install

      - name: Test Unit
        run: npm run test
